---
- name: Installation et Configuration du Monitoring SOC
  hosts: all
  become: yes
  tasks:
    # 1. Création du répertoire de configuration pour Prometheus
    - name: Créer le dossier de configuration Prometheus
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    # 2. Copie de la configuration Prometheus (Celle qui fonctionne !)
    - name: Configurer Prometheus (Targets)
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 5s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['172.17.0.1:9100']
            - job_name: 'cadvisor'
              static_configs:
                - targets: ['172.17.0.1:8080']

    # 3. Lancement de Node Exporter (Métriques Système)
    - name: Lancer le conteneur Node Exporter
      community.docker.docker_container:
        name: node_exporter
        image: prom/node-exporter:latest
        state: started
        restart_policy: always
        published_ports:
          - "9100:9100"

    # 4. Lancement de cAdvisor (Métriques Docker)
    - name: Lancer le conteneur cAdvisor
      community.docker.docker_container:
        name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        state: started
        restart_policy: always
        privileged: yes
        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:rw"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
        published_ports:
          - "8080:8080"

    # 5. Lancement de Prometheus
    - name: Lancer le conteneur Prometheus
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        restart_policy: always
        published_ports:
          - "9090:9090"
        volumes:
          - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

    # 6. Lancement de Grafana (Visualisation)
    - name: Lancer le conteneur Grafana
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: always
        published_ports:
          - "3000:3000"
        env:
          GF_SECURITY_ADMIN_PASSWORD: "Passer123@"
