---
- name: Installation et Configuration du Monitoring SOC
  hosts: all
  become: yes
  tasks:
    - name: Créer le dossier de configuration Prometheus
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    - name: Configurer Prometheus (Cibles 172.17.0.1)
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 5s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['172.17.0.1:9100']
            - job_name: 'cadvisor'
              static_configs:
                - targets: ['172.17.0.1:8080']

    - name: Lancer les conteneurs (NodeExporter, cAdvisor, Prometheus, Grafana)
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        restart_policy: always
        published_ports: "{{ item.ports }}"
        privileged: "{{ item.privileged | default('no') }}"
        volumes: "{{ item.volumes | default([]) }}"
      loop:
        - { name: 'node_exporter', image: 'prom/node-exporter:latest', ports: ["9100:9100"] }
        - { name: 'cadvisor', image: 'gcr.io/cadvisor/cadvisor:latest', ports: ["8080:8080"], privileged: 'yes', volumes: ["/:/rootfs:ro", "/var/run:/var/run:rw", "/sys:/sys:ro", "/var/lib/docker/:/var/lib/docker:ro"] }
        - { name: 'prometheus', image: 'prom/prometheus:latest', ports: ["9090:9090"], volumes: ["/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"] }
        - { name: 'grafana', image: 'grafana/grafana:latest', ports: ["3000:3000"] }

    - name: Lancer le conteneur SonarQube
      community.docker.docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        restart_policy: always
        published_ports:
          - "9000:9000"
      
    
