---
- name: Sécurisation du serveur (Hardening)
  hosts: webserver
  become: yes
  tasks:
    - name: Installation de Fail2Ban et UFW
      apt:
        name: [fail2ban, ufw]
        state: present

    - name: Configuration de UFW (Autoriser SSH, HTTP, Sonar, Grafana)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '22'    # SSH (Pour Ansible)
        - '80'    # Petshop App (Accès utilisateur)
        - '9000'  # SonarQube (Analyse de code)
        - '3000'  # Grafana (Visualisation SOC)
        - '9090'  # Prometheus (Moteur de monitoring)
        - '9100'  # Node Exporter (Métriques serveur)
        - '8080'  # cAdvisor (Métriques Docker)

    - name: Activer le pare-feu UFW
      ufw:
        state: enabled
        policy: deny

    - name: Configurer Fail2Ban pour le SSH
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port = ssh
          filter = sshd
          logpath = /var/log/auth.log
          maxretry = 5
          bantime = 1h

    - name: Redémarrer Fail2Ban
      service:
        name: fail2ban
        state: restarted
